2021-06-18T14:28:50.9358821+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity專案\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T14:28:50.9717863+08:00|116|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T14:28:51.0282167+08:00|116|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T14:28:51.0800524+08:00|116|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T14:28:51.1326565+08:00|116|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T14:29:20.9867864+08:00|116|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2021-06-18T14:29:21.0825302+08:00|116|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 75df80d9351d49a59829d116e17bc7c5(0-0). 
2021-06-18T14:29:21.0825302+08:00|116|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 75df80d9351d49a59829d116e17bc7c5(0-0). 
2021-06-18T14:29:42.2099566+08:00|120|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 75df80d9351d49a59829d116e17bc7c5(0-0). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T14:29:42.2099566+08:00|120|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 75df80d9351d49a59829d116e17bc7c5(0-0). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2021-06-18T14:31:18.3386943+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity專案\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T14:31:18.3716058+08:00|123|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T14:31:18.4254339+08:00|123|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T14:31:18.4767021+08:00|123|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T14:31:18.5305525+08:00|123|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T14:31:48.3866545+08:00|122|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2021-06-18T14:31:48.4510157+08:00|122|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 0a8dc59ed0094e348263f34c7907d442(0-0). 
2021-06-18T14:31:48.4510157+08:00|122|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 0a8dc59ed0094e348263f34c7907d442(0-0). 
2021-06-18T14:32:09.5468336+08:00|122|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 0a8dc59ed0094e348263f34c7907d442(0-0). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T14:32:09.5498032+08:00|122|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 0a8dc59ed0094e348263f34c7907d442(0-0). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2021-06-18T14:33:58.3361199+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity專案\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T14:33:58.3700007+08:00|148|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T14:33:58.4250595+08:00|148|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T14:33:58.4780568+08:00|148|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T14:33:58.5299985+08:00|148|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T14:42:25.4706339+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity專案\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T14:42:25.5045133+08:00|195|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T14:42:25.5585267+08:00|195|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T14:42:25.6103900+08:00|195|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T14:42:25.6617643+08:00|195|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T14:42:55.5166063+08:00|196|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2021-06-18T14:42:55.5684675+08:00|196|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: b82e261de38c4e0694a96b07c4460b06(0-0). 
2021-06-18T14:42:55.5684675+08:00|196|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: b82e261de38c4e0694a96b07c4460b06(0-0). 
2021-06-18T14:43:16.6710795+08:00|199|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: b82e261de38c4e0694a96b07c4460b06(0-0). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T14:43:16.6740723+08:00|199|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: b82e261de38c4e0694a96b07c4460b06(0-0). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2021-06-18T14:55:19.4454234+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity專案\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T14:55:19.4793034+08:00|221|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T14:55:19.5343598+08:00|221|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T14:55:19.5859691+08:00|221|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T14:55:19.6378310+08:00|221|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T14:55:49.4905592+08:00|224|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2021-06-18T14:55:49.5444157+08:00|224|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 5e5b4260d21c47398c15dbf14fd34d0e(0-0). 
2021-06-18T14:55:49.5444157+08:00|224|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 5e5b4260d21c47398c15dbf14fd34d0e(0-0). 
2021-06-18T14:56:10.6386874+08:00|226|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 5e5b4260d21c47398c15dbf14fd34d0e(0-0). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2021-06-18T14:56:10.6386874+08:00|226|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 5e5b4260d21c47398c15dbf14fd34d0e(0-0). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2021-06-18T14:58:45.3239832+08:00|1|INFO|DataSync.Log|Storage folder: D:\unity專案\Eye-Tracking\Assets\TestData\TestStore successfully validated. 
2021-06-18T14:58:45.3568647+08:00|245|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2021-06-18T14:58:45.4107618+08:00|245|INFO|DataSync.Log|MovedFromStorageToSender. 
2021-06-18T14:58:45.4626102+08:00|245|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2021-06-18T14:58:45.5145118+08:00|245|INFO|DataSync.Log|MovedFromBufferToSender. 
2021-06-18T14:59:15.3701161+08:00|245|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2021-06-18T14:59:15.4229745+08:00|245|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: d138cc0a0f7f4dc0b23b18ae94538f7f(0-0). 
2021-06-18T14:59:15.4249700+08:00|245|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: d138cc0a0f7f4dc0b23b18ae94538f7f(0-0). 
